services:
  - type: web
    name: hotel-booking-api
    runtime: docker
    plan: free
    port: 8080
    healthCheckPath: /
    envVars:
      - key: CI_ENV
        value: production
      - key: DB_HOST
        value: aws.connect.psdb.cloud
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: hotel_booking
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true

  - type: web
    name: hotel-booking-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://hotel-booking-api-1-zmcs.onrender.com
